name: InfernoCore
main: inferno.network.Main
version: 1.0
commands:
    tokens:
        aliases: [token, t]
    cosmetictokens:
        aliases: [cosmetictoken, ct]
    ban:
    unban:
    kick:
    warn:
    friend: